/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChangeCredentialsRequest {
  currentPassword?: string;
  /** @pattern ^[a-zA-Z0-9._-]{5,30}$ */
  newLogin?: string;
  /**
   * @minLength 6
   * @maxLength 2147483647
   */
  newPassword?: string;
}
