/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChoiceStatsDto {
  id?: number;
  /** @minimum 0 */
  count: number;
}
