/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChoiceDto {
  id?: number;
  name: string;
  /** @minimum 0 */
  position: number;
}
