/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChoiceDto } from './choiceDto';

export type MultiChoiceQuestionDtoAllOf = {
  possibleChoices?: ChoiceDto[];
};
