/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QuestionStatsDto } from './questionStatsDto';
import type { MultiChoiceQuestionStatsDtoAllOf } from './multiChoiceQuestionStatsDtoAllOf';

export type MultiChoiceQuestionStatsDto = QuestionStatsDto & MultiChoiceQuestionStatsDtoAllOf & Required<Pick<QuestionStatsDto & MultiChoiceQuestionStatsDtoAllOf, 'choiceStats'>>;
