/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AnswerDto } from './answerDto';
import type { MultiChoiceAnswerDtoAllOf } from './multiChoiceAnswerDtoAllOf';

export type MultiChoiceAnswerDto = AnswerDto & MultiChoiceAnswerDtoAllOf & Required<Pick<AnswerDto & MultiChoiceAnswerDtoAllOf, 'selectedChoiceIds'>>;
