/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QuestionDto } from './questionDto';
import type { MultiChoiceQuestionDtoAllOf } from './multiChoiceQuestionDtoAllOf';

export type MultiChoiceQuestionDto = QuestionDto & MultiChoiceQuestionDtoAllOf & Required<Pick<QuestionDto & MultiChoiceQuestionDtoAllOf, 'possibleChoices'>>;
