/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PollCreateRequest {
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  description?: string;
}
