/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MultiChoiceQuestionDto } from './multiChoiceQuestionDto';
import type { SingleChoiceQuestionDto } from './singleChoiceQuestionDto';
import type { TextQuestionDto } from './textQuestionDto';

export type PollResponseQuestionsItem = MultiChoiceQuestionDto | SingleChoiceQuestionDto | TextQuestionDto;
