/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PollResponseStatus = typeof PollResponseStatus[keyof typeof PollResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PollResponseStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  FINISHED: 'FINISHED',
} as const;
