/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface QuestionStatsDto {
  questionId: number;
  answerCount: number;
  dtype: string;
}
