/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ShortPollResponseStatus } from './shortPollResponseStatus';

export interface ShortPollResponse {
  id: number;
  createdDate: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  description?: string;
  status: ShortPollResponseStatus;
}
