/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QuestionDto } from './questionDto';
import type { SingleChoiceQuestionDtoAllOf } from './singleChoiceQuestionDtoAllOf';

export type SingleChoiceQuestionDto = QuestionDto & SingleChoiceQuestionDtoAllOf & Required<Pick<QuestionDto & SingleChoiceQuestionDtoAllOf, 'possibleChoices'>>;
