/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QuestionStatsDto } from './questionStatsDto';
import type { SingleChoiceQuestionStatsDtoAllOf } from './singleChoiceQuestionStatsDtoAllOf';

export type SingleChoiceQuestionStatsDto = QuestionStatsDto & SingleChoiceQuestionStatsDtoAllOf & Required<Pick<QuestionStatsDto & SingleChoiceQuestionStatsDtoAllOf, 'choiceStats'>>;
