/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AnswerDto } from './answerDto';
import type { SingleChoiceAnswerDtoAllOf } from './singleChoiceAnswerDtoAllOf';

export type SingleChoiceAnswerDto = AnswerDto & SingleChoiceAnswerDtoAllOf & Required<Pick<AnswerDto & SingleChoiceAnswerDtoAllOf, 'selectedChoiceId'>>;
