/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MultiChoiceQuestionStatsDto } from './multiChoiceQuestionStatsDto';
import type { SingleChoiceQuestionStatsDto } from './singleChoiceQuestionStatsDto';
import type { TextQuestionStatsDto } from './textQuestionStatsDto';

export type StatsResponseStatsItem = MultiChoiceQuestionStatsDto | SingleChoiceQuestionStatsDto | TextQuestionStatsDto;
