/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MultiChoiceAnswerDto } from './multiChoiceAnswerDto';
import type { SingleChoiceAnswerDto } from './singleChoiceAnswerDto';
import type { TextAnswerDto } from './textAnswerDto';

export type SubmissionCreateRequestAnswersItem = MultiChoiceAnswerDto | SingleChoiceAnswerDto | TextAnswerDto;
