/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SubmissionCreateRequestAnswersItem } from './submissionCreateRequestAnswersItem';

export interface SubmissionCreateRequest {
  answers: SubmissionCreateRequestAnswersItem[];
}
