/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QuestionStatsDto } from './questionStatsDto';
import type { TextQuestionStatsDtoAllOf } from './textQuestionStatsDtoAllOf';

export type TextQuestionStatsDto = QuestionStatsDto & TextQuestionStatsDtoAllOf & Required<Pick<QuestionStatsDto & TextQuestionStatsDtoAllOf, 'tags' | 'tagsCount'>>;
