/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AnswerDto } from './answerDto';
import type { TextAnswerDtoAllOf } from './textAnswerDtoAllOf';

export type TextAnswerDto = AnswerDto & TextAnswerDtoAllOf & Required<Pick<AnswerDto & TextAnswerDtoAllOf, 'value'>>;
