/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AiTextQuestionSummaryTagDto } from './aiTextQuestionSummaryTagDto';

export type TextQuestionStatsDtoAllOf = {
  tagsCount?: number;
  tags?: AiTextQuestionSummaryTagDto[];
};
