/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserResponseRolesItem = typeof UserResponseRolesItem[keyof typeof UserResponseRolesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseRolesItem = {
  ANONYMOUS: 'ANONYMOUS',
  REGISTERED: 'REGISTERED',
  ADMIN: 'ADMIN',
} as const;
